# # FROM oven/bun:latest AS base
FROM oven/bun:1-alpine AS base
WORKDIR /app

# Copy only files needed for install to cache this layer
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# STAGE 2: Build/Run
# FROM oven/bun:latest AS release
FROM oven/bun:1-alpine AS release

WORKDIR /app

# Copy node_modules from base stage
COPY --from=base /app/node_modules ./node_modules
# Copy your source code
COPY . .

# Set environment to production
ENV NODE_ENV=production

# Security: Run as non-root user
USER bun

# The port your Elysia app listens on
EXPOSE 3000

CMD ["bun", "run", "src/index.ts"]

